{{ config(materialized='incremental', incremental_strategy='merge', unique_key='GAME_ID') }}

WITH REGEX_CTE AS (
    SELECT 
    GAME_ID::STRING AS GAME_ID,
    REGEXP_SUBSTR(CHESS_MATCH, '\\[TimeControl "([^"]+)"\\]', 1, 1, 'e', 1)::VARCHAR AS GAME_TYPE_SECS,
    TO_DATE(REGEXP_SUBSTR(CHESS_MATCH, '\\[UTCDate "([^"]+)"\\]', 1, 1, 'e', 1),'YYYY.MM.DD')::VARCHAR AS START_DATE_UTC,
    TO_TIME(REGEXP_SUBSTR(CHESS_MATCH, '\\[UTCTime "([^"]+)"\\]', 1, 1, 'e', 1),'HH24:MI:SS')::VARCHAR AS START_TIME_UTC,
    TO_DATE(REGEXP_SUBSTR(CHESS_MATCH, '\\[EndDate "([^"]+)"\\]', 1, 1, 'e', 1),'YYYY.MM.DD')::VARCHAR AS END_DATE_UTC,
    TO_TIME(REGEXP_SUBSTR(CHESS_MATCH, '\\[EndTime "([^"]+)"\\]', 1, 1, 'e', 1),'HH24:MI:SS')::VARCHAR AS END_TIME_UTC,
    REGEXP_SUBSTR(CHESS_MATCH, '\\[White "([^"]+)"\\]', 1, 1, 'e', 1)::VARCHAR AS WHITE_PLAYER,
    REGEXP_SUBSTR(CHESS_MATCH, '\\[WhiteElo "([^"]+)"\\]', 1, 1, 'e', 1)::VARCHAR AS WHITE_PLAYER_ELO,
    REGEXP_SUBSTR(CHESS_MATCH, '\\[Black "([^"]+)"\\]', 1, 1, 'e', 1)::VARCHAR AS BLACK_PLAYER,
    REGEXP_SUBSTR(CHESS_MATCH, '\\[BlackElo "([^"]+)"\\]', 1, 1, 'e', 1)::VARCHAR AS BLACK_PLAYER_ELO,
    REGEXP_SUBSTR(CHESS_MATCH, '\\[Result "([^"]+)"\\]', 1, 1, 'e', 1)::VARCHAR AS GAME_RESULT,
    REGEXP_SUBSTR(CHESS_MATCH,'\\[Termination "([^"]+)"\\]',1,1,'e',1) AS TERMINATION_RAW,
    REGEXP_SUBSTR(CHESS_MATCH, '\\[ECO "([^"]+)"\\]', 1, 1, 'e', 1)::VARCHAR AS ECO_CODE,
    REGEXP_SUBSTR(CHESS_MATCH, '\\[ECOUrl "([^"]+)"\\]', 1, 1, 'e', 1)::VARCHAR AS ECO_URL,
    REGEXP_SUBSTR(CHESS_MATCH, '\\[Link "([^"]+)"\\]', 1, 1, 'e', 1)::VARCHAR AS GAME_URL,
    REGEXP_SUBSTR(CHESS_MATCH,'\\r?\\n\\r?\\n(.+)$',1,1,'es',1)::VARCHAR AS CHESS_MATCH
FROM {{ source('chessdotcom', 'raw_raw_chess_matches') }}

{% if is_incremental() %}
WHERE GAME_ID NOT IN (SELECT GAME_ID FROM {{ this }})
{% endif %}
),

    TERMINATION_CASES AS (
        SELECT
            GAME_ID,
            TRIM(REGEXP_REPLACE(TERMINATION_RAW,'^(.*\\bby\\s+|.*-\\s*|.*\\bwon\\s+)',''))::VARCHAR AS TERMINATION
        FROM REGEX_CTE
    )

SELECT 
    R.GAME_ID::VARCHAR AS GAME_ID,
    R.GAME_TYPE_SECS::VARCHAR AS GAME_TYPE_SECS,
    R.START_DATE_UTC::VARCHAR AS START_DATE_UTC,
    R.START_TIME_UTC::VARCHAR AS START_TIME_UTC,
    R.END_DATE_UTC::VARCHAR AS END_DATE_UTC,
    R.END_TIME_UTC::VARCHAR AS END_TIME_UTC,
    R.WHITE_PLAYER::VARCHAR AS WHITE_PLAYER,
    R.WHITE_PLAYER_ELO::VARCHAR AS WHITE_PLAYER_ELO,
    R.BLACK_PLAYER::VARCHAR AS BLACK_PLAYER,
    R.BLACK_PLAYER_ELO::VARCHAR AS BLACK_PLAYER_ELO,
    R.GAME_RESULT::VARCHAR AS GAME_RESULT,
    T.TERMINATION::VARCHAR AS TERMINATION,
    R.ECO_CODE::VARCHAR AS ECO_CODE,
    R.ECO_URL::VARCHAR AS ECO_URL,
    R.GAME_URL::VARCHAR AS GAME_URL,
    R.CHESS_MATCH::VARCHAR AS CHESS_MATCH
FROM REGEX_CTE AS R
INNER JOIN TERMINATION_CASES AS T
ON R.GAME_ID = T.GAME_ID

