{{ config(materialized='incremental', incremental_strategy='merge', unique_key='GAME_ID') }}

SELECT 
    GAME_ID::STRING AS GAME_ID,
    GAME_TYPE_SECS::INT AS GAME_TYPE_SECS,
    TO_TIMESTAMP(START_DATE_UTC || ' ' || START_TIME_UTC) AS START_DATETIME_UTC,
    TO_TIMESTAMP(END_DATE_UTC || ' ' || END_TIME_UTC) AS END_DATETIME_UTC,
    WHITE_PLAYER::VARCHAR AS WHITE_PLAYER,
    WHITE_PLAYER_ELO::INT AS WHITE_PLAYER_ELO,
    BLACK_PLAYER::VARCHAR AS BLACK_PLAYER,
    BLACK_PLAYER_ELO::INT AS BLACK_PLAYER_ELO,
    CASE 
        WHEN GAME_RESULT::VARCHAR = '1/2-1/2' THEN 'Draw'
        WHEN GAME_RESULT::VARCHAR = '1-0' THEN WHITE_PLAYER
        WHEN GAME_RESULT::VARCHAR = '0-1' THEN BLACK_PLAYER
        ELSE GAME_RESULT::VARCHAR
    END AS GAME_RESULT,
    TERMINATION::VARCHAR AS TERMINATION,
    ECO_CODE::VARCHAR AS ECO_CODE,
    ECO_URL::VARCHAR AS ECO_URL,
    GAME_URL::VARCHAR AS GAME_URL,
    CHESS_MATCH::VARCHAR AS CHESS_MATCH
FROM {{ ref('raw_chess_matches') }}

{% if is_incremental() %}
WHERE GAME_ID NOT IN (SELECT GAME_ID FROM {{ this }})
{% endif %}