version: 2

sources:
  - name: chessdotcom
    description: "This source contains the raw data from the Chess.com API."
    tables:
      - name: raw_raw_chess_matches
        description: "This table contains the raw data from the Chess.com API, including information about chess matches."
        tests:
          - unique:
              column_name: game_id
          - not_null:
              column_name: game_id
        columns:
          - name: game_id
            description: "The unique identifier for each chess match."
          - name: chess_match
            description: "The chess match data in STRING format."
          - name: fetched_at
            description: "The timestamp when the data was fetched from S3 API."
            